// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'colorButtonYellow': string;
  'fullWidth': string;
  'root': string;
  'sizeL': string;
  'sizeM': string;
}
export const cssExports: CssExports;
export default cssExports;
