enum actionType {
	FETCH_TYPES = 'FETCH_TYPES',
	FETCH_TYPES_RESOLVE = 'FETCH_TYPES_RESOLVE',
	FETCH_TYPES_REJECT = 'FETCH_TYPES_REJECT',
	GET_POKEMONS = 'GET_POKEMONS',
} 

export default actionType;