enum actionType {
	ADD_POKEMONS = 'ADD_POKEMONS',
	FETCH_TYPES = 'FETCH_TYPES',
	FETCH_TYPES_RESOLVE = 'FETCH_TYPES_RESOLVE',
	FETCH_TYPES_REJECT = 'FETCH_TYPES_REJECT',
} 

export default actionType;