// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'item_cardBox': string;
  'item_cardBox__number': string;
  'root': string;
  'root__cardBoxColumn': string;
  'root__cardBoxRow': string;
  'root__cartAbilitiesBox': string;
  'root__cartAbilitiesBox_item': string;
  'root__cartAbilitiesHp': string;
  'root__chargeLoader': string;
  'root__circle': string;
  'root__close': string;
  'root__content': string;
  'root__image': string;
  'root__info': string;
  'root__pAbilities': string;
  'root__subtitle': string;
  'root__title': string;
  'root__wrapTitle': string;
}
export const cssExports: CssExports;
export default cssExports;
