// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'root': string;
  'root__contentSubtitle': string;
  'root__contentTitle': string;
  'root__wrap': string;
  'root__wrapText': string;
}
export const cssExports: CssExports;
export default cssExports;
