// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'root': string;
  'sizeL': string;
  'sizeM': string;
  'sizeS': string;
  'sizeXL': string;
  'sizeXS': string;
  'sizeXXS': string;
}
export const cssExports: CssExports;
export default cssExports;
