// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'menuWrap': string;
  'menuWrap__linck': string;
  'menuWrap__linck_active': string;
  'root': string;
  'root__pokemonLogo': string;
  'root__wrap': string;
}
export const cssExports: CssExports;
export default cssExports;
