// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'errorMess': string;
  'loadMess': string;
  'root': string;
  'root__container': string;
  'root__title': string;
  'root__wrap': string;
  'root__wrapCard': string;
  'root__wrapCardsContainer': string;
}
export const cssExports: CssExports;
export default cssExports;
