// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'root': string;
  'root__backImg': string;
  'root__buttonReturn': string;
  'root__content': string;
  'root__imageTeam': string;
  'root__title': string;
}
export const cssExports: CssExports;
export default cssExports;
